apiVersion: v1
kind: Service
metadata:
  name: {{ include "flightdeck-solr.fullname" . }}
  labels:
    {{- include "flightdeck-solr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP  }}
  clusterIP: {{ . | quote }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: solr
      protocol: TCP
      name: solr
  selector:
    {{- include "flightdeck-solr.selectorLabels" . | nindent 4 }}
