{{- $fullName := include "flightdeck-web.fullname" . -}}
{{- $labels := include "flightdeck-web.labels" . -}}
{{- range $name, $job := .Values.postDeployJobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $fullName }}-{{ lower $name }}"
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    {{- with $job.hookWeight }}
    "helm.sh/hook-weight": {{ . | quote }}
    {{- end }}
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- $labels | nindent 14 }}
    spec:
      serviceAccountName: {{ include "flightdeck-web.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      {{- with $job.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $job.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $job.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - image: {{ include "flightdeck-web.image" $ | quote }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          name: {{ lower $name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          {{- if $job.command }}
          command: {{ $job.command }}
          {{- end }}
          {{- with $job.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /config/web
              name: vol-config-flightdeck-web
          {{- if $.Values.extraVolumeMounts }}
            {{- toYaml $.Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      volumes:
        - name: vol-config-flightdeck-web
          configMap:
            name: '{{ $fullName }}-config'
      {{- if $.Values.extraVolumes }}
        {{- toYaml $.Values.extraVolumes | nindent 8 }}
      {{- end }}
{{- end }}