{{- if .Values.varnish.enabled -}}
{{- $fullName := include "flightdeck-web.fullname" . -}}
{{- $secretName := print $fullName "-varnish-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  labels:
    {{- include "flightdeck-web.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existingValue := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if or (not $existingValue) (not $existingValue.data) }}
  secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ else }}
  secret: {{ index $existingValue.data "secret" }}
  {{ end }}
{{- end }}

