{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flightdeck-web.fullname" . }}
  labels:
    {{- include "flightdeck-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
  {{- if .Values.varnish.enabled }}
    - port: {{ .Values.service.varnishPort }}
      targetPort: {{ .Values.service.varnishPort }}
      protocol: TCP
      name: varnish
    - port: {{ .Values.service.varnishControlPort }}
      targetPort: {{ .Values.service.varnishControlPort }}
      protocol: TCP
      name: varnish-control
  {{- end }}
  selector:
    {{- include "flightdeck-web.selectorLabels" . | nindent 4 }}
{{- end }}
