apiVersion: v1
data:
  flightdeck-db.yml: |
    mysql_root_password_file: "/config/mysql-admin/root-pass.txt"
    {{- with .Values.config.mysql_databases }}
    mysql_databases:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.config.mysql_users }}
    mysql_users:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    mysql_key_buffer_size: "{{ .Values.config.mysql_key_buffer_size }}"
    mysql_max_allowed_packet: "{{ .Values.config.mysql_max_allowed_packet }}"
    mysql_table_open_cache: "{{ .Values.config.mysql_table_open_cache }}"
    mysql_query_cache_size: "{{ .Values.config.mysql_query_cache_size }}"
    mysql_binlog_expire_logs_seconds: {{ .Values.config.mysql_binlog_expire_logs_seconds | default "3600" | quote }}
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "flightdeck-db.fullname" . }}-config
