# Default values for flightdeck-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ten7/flightdeck-db-10.6
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  mysql_root_password_file: "/config/mysql-admin/root-pass.txt"
  mysql_databases: []
#    - name: "my_db"
#      encoding: "latin1"
#      collation: "latin1_general_ci"
  mysql_users: []
#    - name: "my_user"
#      host: "%"
#      passwordFile: "/config/my-mysql/db-pass.txt"
#      priv: "my_db.*:ALL"
  mysql_key_buffer_size: "256M"
  mysql_max_allowed_packet: "64M"
  mysql_table_open_cache: "256"
  mysql_query_cache_size: "0"
  mysql_binlog_expire_logs_seconds: "3600"


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  clusterIP: None
  port: 3306

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits: {}
  requests:
    cpu: 650m
    memory: 1000Mi


volumeClaimTemplate:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi

persistence:
  enabled: false
  labels:
    # Add default labels for the volumeClaimTemplate of the StatefulSet
    enabled: false
  annotations: {}

extraVolumes:
# - name: my-mysql
#   secret:
#     secretName: my-mysql

extraVolumeMounts:
# - name: my-mysql
#   mountPath: /config/my-mysql
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
